### PR TITLE
Add ability for users to input custom properties to readwise imports

### PR DESCRIPTION
**Pull request by JFKelly68**
I wanted to be able to add a custom property to the readwise imports, specifically a property `referrer: [[Readwise]]`. This was my attempt to do so.

I would love some insight into how to test this locally. As it stands, it would not be styled properly and truly I haven't confirmed that this works. I tried running it locally using the npm scripts, but it didn't work. What I haven't tried is loading the package manually, via manifest and my personal github.

I will try that tomorrow, but in the off chance you take a look at this in the meantime to see if this is something you'd even want. Otherwise, I will just continue to try and run it from my personal repo.

### CODE REVIEW

**Comment by benjypng** [comment]
Hi! Thanks for the PR!
I think as Readwise is coming up with their own plugin soon, I think there's no need to add further functions!

As for running it locally, I'm assuming you have already cloned the plugin and made the changes. Next you can run `npm install && npm run build`. It will then produce a `dist` directory. 

Then you go to Logseq and click load manual plugin. Then choose the parent folder that contains `package.json`. The plugin should then appear in the list.

**Comment by JFKelly68** [comment]
ah, didn't realize Readwise was making a proprietary. Did they announce that in some forum I should be aware of? 

And I tried that approach of `npm i && npm run build` but it seemed to break your version. I had given it a different name to try and prevent scope overlap, but perhaps I need to uninstall yours first and then try again.

**Comment by benjypng** [comment]
Yup they are! I think can find it in the Discord. It is quite open knowledge at this point.

Yes, you should only run one instance of the plugin at any one time. Suggest to uninstall the marketplace one, go to `.logseq/settings` and delete `logseq-readwise-plugin.json`, before you load the manual plugin.

**Comment by logseqramses** [comment]
@hkgnp I don't think the Logseq plugin is high on the Readwise roadmap. I've spoken to some team members and they were so impressed by your plugin that they prioritized some other things instead.

Personally, I really miss not being able to set custom metadata. It would be amazing if you could add support for it.

Selective sync is another pain point, but I guess that _is_ something that has to be done on the Readwise side.

**Comment by benjypng** [comment]
This is implemented in v4+.

**Pull request closed without merging**
